CREATE TABLE `performance_validations` (
	`id` varchar(36) NOT NULL,
	`project_id` int NOT NULL,
	`calculation_id` varchar(100) NOT NULL,
	`annual_generation_gwh` varchar(20),
	`capacity_factor_percent` varchar(20),
	`performance_ratio_percent` varchar(20),
	`specific_yield_kwh_kwp` varchar(20),
	`contractor_claim_gwh` varchar(20),
	`variance_percent` varchar(20),
	`variance_gwh` varchar(20),
	`flag_triggered` int DEFAULT 0,
	`confidence_level` varchar(20),
	`dc_capacity_mw` varchar(20),
	`ac_capacity_mw` varchar(20),
	`module_model` varchar(255),
	`inverter_model` varchar(255),
	`tracking_type` varchar(50),
	`total_system_losses_percent` varchar(20),
	`parameters_extracted_count` int,
	`parameters_assumed_count` int,
	`confidence_score` varchar(20),
	`weather_data_source` varchar(255),
	`ghi_annual_kwh_m2` varchar(20),
	`poa_annual_kwh_m2` varchar(20),
	`monthly_profile` text,
	`model_used` varchar(50),
	`pysam_version` varchar(20),
	`calculation_time_seconds` varchar(20),
	`warnings` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `performance_validations_id` PRIMARY KEY(`id`)
);
