CREATE TABLE `financial_data` (
	`id` varchar(36) NOT NULL,
	`project_id` int NOT NULL,
	`total_capex_usd` varchar(20),
	`modules_usd` varchar(20),
	`inverters_usd` varchar(20),
	`trackers_usd` varchar(20),
	`civil_works_usd` varchar(20),
	`grid_connection_usd` varchar(20),
	`development_costs_usd` varchar(20),
	`other_capex_usd` varchar(20),
	`total_opex_annual_usd` varchar(20),
	`om_usd` varchar(20),
	`insurance_usd` varchar(20),
	`land_lease_usd` varchar(20),
	`asset_management_usd` varchar(20),
	`other_opex_usd` varchar(20),
	`capex_per_watt_usd` varchar(20),
	`opex_per_mwh_usd` varchar(20),
	`original_currency` varchar(10),
	`exchange_rate_to_usd` varchar(20),
	`cost_year` int,
	`escalation_rate_percent` varchar(20),
	`source_document_id` varchar(36),
	`confidence` varchar(20),
	`extraction_method` varchar(50),
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_data_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `performance_parameters` (
	`id` varchar(36) NOT NULL,
	`project_id` int NOT NULL,
	`dc_capacity_mw` varchar(20),
	`ac_capacity_mw` varchar(20),
	`module_model` varchar(255),
	`module_power_watts` varchar(20),
	`module_count` int,
	`inverter_model` varchar(255),
	`inverter_power_kw` varchar(20),
	`inverter_count` int,
	`tracking_type` varchar(50),
	`tilt_angle_degrees` varchar(20),
	`azimuth_degrees` varchar(20),
	`latitude` varchar(20),
	`longitude` varchar(20),
	`site_name` varchar(255),
	`elevation_m` varchar(20),
	`timezone` varchar(50),
	`system_losses_percent` varchar(20),
	`degradation_rate_percent` varchar(20),
	`availability_percent` varchar(20),
	`soiling_loss_percent` varchar(20),
	`weather_file_url` varchar(500),
	`ghi_annual_kwh_m2` varchar(20),
	`dni_annual_kwh_m2` varchar(20),
	`temperature_ambient_c` varchar(20),
	`p50_generation_gwh` varchar(20),
	`p90_generation_gwh` varchar(20),
	`capacity_factor_percent` varchar(20),
	`specific_yield_kwh_kwp` varchar(20),
	`source_document_id` varchar(36),
	`confidence` varchar(20),
	`extraction_method` varchar(50),
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `performance_parameters_id` PRIMARY KEY(`id`)
);
