CREATE TABLE `weather_files` (
	`id` varchar(36) NOT NULL,
	`project_id` int NOT NULL,
	`file_key` varchar(500) NOT NULL,
	`file_url` varchar(500) NOT NULL,
	`file_name` varchar(255) NOT NULL,
	`file_size_bytes` int NOT NULL,
	`source_type` varchar(50) NOT NULL,
	`source_document_id` varchar(36),
	`extracted_url` varchar(500),
	`original_format` varchar(50),
	`converted_format` varchar(50) DEFAULT 'sam_csv',
	`converted_file_key` varchar(500),
	`latitude` varchar(20),
	`longitude` varchar(20),
	`elevation` varchar(20),
	`timezone` varchar(20),
	`location_name` varchar(255),
	`quality_score` varchar(20),
	`record_count` int,
	`missing_hours` int,
	`outlier_count` int,
	`validation_warnings` text,
	`status` varchar(20) DEFAULT 'pending',
	`processing_error` text,
	`used_in_validation_id` varchar(36),
	`is_active` int DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `weather_files_id` PRIMARY KEY(`id`)
);
